steps:
  - name: node:10
    entrypoint: yarn
    args:
      - install
    id: "client-install"
    dir: "client/"
  - name: node:10
    entrypoint: yarn
    args:
      - create-env
    id: "client-env"
    dir: "client/"
    env:
      - "REACT_APP_GOOGLE_MAPS_API_KEY=${_GOOGLE_MAPS_API_KEY}"
      - "REACT_APP_MICROAPPS_CLIENT_ID=${_MICROAPPS_CLIENT_ID}"
    waitFor: ["client-install"]
  - name: node:10
    entrypoint: yarn
    args:
      - build
    id: "client-build"
    dir: "client/"
    waitFor: ["client-env"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "client/"
    waitFor: ["client-build"]
    timeout: 300s
  - name: node:10
    entrypoint: yarn
    args:
      - install
    id: "server-build"
    dir: "server/"
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    dir: "server/"
    waitFor: ["server-build"]
    timeout: 300s

options:
  machineType: "N1_HIGHCPU_8"
